name: dekon
description: "Offline-first inventory and POS app."
publish_to: 'none'
version: 0.1.4+5

environment:
  sdk: ^3.12.1

dependencies:
  crypto: ^3.0.7
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  http: ^1.6.0
  mobile_scanner: ^7.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  shelf: ^1.4.2
  sqflite: ^2.4.3
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.1

flutter:
  uses-material-design: true
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Variable.ttf
